### ISSUE TITLE
Array types not working as per documentation

### ISSUE THREAD

**Issue by HaroldStruwig** [sindresorhus/dot-prop#100]
Documentation:
```ts
const object = { foo: { bar: 'b', baz: 'x' } };
setProperty(object, 'foo.biz.0', 'a');
console.log(object);
//=> {foo: {bar: 'b', baz: 'x', biz: ['a']}}
```

Actual:
```ts
const object = { foo: { bar: 'b', baz: 'x' } };
setProperty(object, 'foo.biz.0', 'a');
console.log(object);
//=> {"foo": {"bar": "b", "baz": "x", "biz": { "0": "a" } }}
```

Also the following results in a exception:
```ts
const object = { foo: { bar: 'b', baz: 'x', biz: [] } };
setProperty(object, 'foo.biz.0', 'a');
console.log(object);
```
```
core.js:6498 ERROR Error: Cannot use string index
    at assertNotStringIndex (index.js:169:1)
    at setProperty (index.js:220:1)
```

**Comment by HaroldStruwig** [comment]
Closing as I made a mistake with syntax - path should contain `[]` eg. `foo.biz[0]` instead of `foo.biz.0`
