### ISSUE TITLE
Breaks node4 compatability (4.2.6)

### ISSUE THREAD

**Issue by hahcho** [sindresorhus/dot-prop#69]
I do not know if this is something that you are after since this node version (4.2.6) is no longer officially supported but the `4.2.1` release breaks the package with this error:

```
TypeError: disallowedKeys.includes is not a function
    at Array.some (native)
    at pathSegments.some (/usr/src/app/node_modules/dot-prop/index.js:10:51)
    at Object.get (/usr/src/app/node_modules/dot-prop/index.js:40:19)
    at UpdateNotifier.check (/usr/src/app/node_modules/update-notifier/index.js:78:16)
    at __dirname.check.checkNpm.then.checkNpm.module.exports.options (/usr/src/app/node_modules/update-notifier/index.js:151:17)
    at Object.<anonymous> (/usr/src/app/node_modules/nodemon/bin/nodemon.js:15:29)
```

The issue comes from this https://github.com/sindresorhus/dot-prop/commit/3039c8c07f6fdaa8b595ec869ae0895686a7a0f2#diff-168726dbe96b3ce427e7fedce31bb0bcR10

It is kind of a bummer since`nodemon` defines its dependency to this package as '^...' through `update-notifier` which will automatically pick the latest minor version which is `4.2.1`

`4.2.0` works fine.

**Comment by sindresorhus** [comment]
That's a problem for you or `nodemon` to handle. This package correctly defined Node.js 8 when that change was made.
